"""Build the searchable documentation catalog from package manifests."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SRC_ROOT = ROOT / "src"
DEFAULT_MARKDOWN = ROOT / "docs" / "gallery.md"
DEFAULT_JSON = ROOT / "docs" / "gallery.json"

if str(SRC_ROOT) not in sys.path:
    sys.path.insert(0, str(SRC_ROOT))

from tdimagefx import Version  # noqa: E402


def load_entries() -> list[dict]:
    latest: dict[str, tuple[Version, dict]] = {}
    for path in sorted((ROOT / "packages").glob("*/*/package.json")):
        manifest = json.loads(path.read_text(encoding="utf-8"))
        package_id = manifest["id"]
        version = Version.parse(manifest["version"])
        current = latest.get(package_id)
        if current is not None and version == current[0] and not version.exactly_equals(current[0]):
            raise ValueError(
                f"Ambiguous package versions with equal precedence for {package_id}: "
                f"{current[0]} and {version}"
            )
        if current is None or current[0] < version:
            latest[package_id] = (version, manifest)

    entries: list[dict] = []
    for package_id in sorted(latest):
        manifest = latest[package_id][1]
        processing = manifest.get("processing") or {
            "model": "single_pass", "gpu_cost": "low", "capabilities": [], "history_frames": 0,
        }
        entries.append({
            "id": manifest["id"],
            "name": manifest["name"],
            "version": manifest["version"],
            "category": manifest["category"],
            "description": manifest["description"],
            "tags": manifest["tags"],
            "processing_model": processing["model"],
            "gpu_cost": processing["gpu_cost"],
            "capabilities": processing.get("capabilities", []),
            "inputs": len(manifest["inputs"]),
            "parameters": [parameter.get("label", parameter.get("name", parameter["id"])) for parameter in manifest["parameters"]],
            "compatibility": manifest["compatibility"],
            "preview": f"gallery/{manifest['id']}.png",
        })
    return entries


def render_markdown(entries: list[dict]) -> str:
    categories: dict[str, list[dict]] = {}
    for entry in entries:
        categories.setdefault(entry["category"], []).append(entry)
    lines = [
        "# Effect gallery",
        "",
        "This file is generated by `python tools/build_gallery.py`. Search `docs/gallery.json` programmatically or use this category index.",
        "",
        f"Current catalog: **{len(entries)} effects** across **{len(categories)} categories**.",
        "",
        "GPU cost is a relative authoring hint; measure on the target GPU before a show.",
        "",
    ]
    for category in sorted(categories):
        lines.extend([f"## {category.title()}", ""])
        for entry in sorted(categories[category], key=lambda item: item["name"].casefold()):
            capability_text = ", ".join(entry["capabilities"]) or "none"
            tag_text = ", ".join(entry["tags"])
            lines.extend([
                f"### {entry['name']}",
                "",
                f"![{entry['name']} preview]({entry['preview']})",
                "",
                entry["description"],
                "",
                f"- Package: `{entry['id']}@{entry['version']}`",
                f"- Processing: `{entry['processing_model']}` · GPU cost: `{entry['gpu_cost']}`",
                f"- Capabilities: {capability_text}",
                f"- Tags: {tag_text}",
                f"- Inputs: {entry['inputs']} · Parameters: {', '.join(entry['parameters'])}",
                "",
            ])
    return "\n".join(lines).rstrip() + "\n"


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--markdown", type=Path, default=DEFAULT_MARKDOWN)
    parser.add_argument("--json", type=Path, default=DEFAULT_JSON)
    parser.add_argument("--check", action="store_true", help="Fail if generated files are out of date")
    return parser


def main() -> int:
    args = _parser().parse_args()
    entries = load_entries()
    markdown = render_markdown(entries)
    payload = json.dumps({"schema_version": 1, "effects": entries}, indent=2, ensure_ascii=False) + "\n"
    stale = []
    for path, content in ((args.markdown, markdown), (args.json, payload)):
        if args.check:
            if not path.is_file() or path.read_text(encoding="utf-8") != content:
                stale.append(path)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8", newline="\n")
    if stale:
        print("Generated gallery is stale: " + ", ".join(str(path) for path in stale))
        return 1
    print(f"Gallery contains {len(entries)} effects")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
