"""Scaffold a TD ImageFX package without overwriting existing work.

Examples:
    python tools/new_effect.py bloom-lite "Bloom Lite" stylize
    python tools/new_effect.py echo-lite "Echo Lite" temporal --model temporal \
        --capability history --history-frames 1
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SRC_ROOT = ROOT / "src"
PACKAGES = ROOT / "packages"
PROCESSING_MODELS = ("single_pass", "multi_pass", "temporal", "simulation", "adapter")
GPU_COSTS = ("low", "medium", "high", "extreme")
CAPABILITIES = (
    "multi_pass", "history", "second_input", "transition", "displacement", "depth",
    "normal", "flow", "simulation", "audio", "native_plugin", "network", "python",
)
SLUG_RE = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")

if str(SRC_ROOT) not in sys.path:
    sys.path.insert(0, str(SRC_ROOT))

from tdimagefx import PackageManifest  # noqa: E402
from tdimagefx.errors import ValidationError  # noqa: E402
from tdimagefx.semver import Version  # noqa: E402


SHADER_TEMPLATE = """// Generated by tools/new_effect.py. Replace the sample transform with the effect.
uniform float uMix;

layout(location = 0) out vec4 fragColor;

void main()
{
    vec2 uv = vUV.st;
    vec4 source = texture(sTD2DInputs[0], uv);
    vec4 effected = source;
    fragColor = TDOutputSwizzle(mix(source, effected, clamp(uMix, 0.0, 1.0)));
}
"""


SECOND_PASS_TEMPLATE = """// Second-pass scaffold. Input 0 is the previous pass; input 1 is the source.
uniform float uMix;

layout(location = 0) out vec4 fragColor;

void main()
{
    vec2 uv = vUV.st;
    vec4 previous = texture(sTD2DInputs[0], uv);
    vec4 source = texture(sTD2DInputs[1], uv);
    fragColor = TDOutputSwizzle(mix(source, previous, clamp(uMix, 0.0, 1.0)));
}
"""


TEMPORAL_TEMPLATE = """// Temporal scaffold. Input 0 is the current frame; input 1 is history.
uniform float uMix;

layout(location = 0) out vec4 fragColor;

void main()
{
    vec2 uv = vUV.st;
    vec4 currentFrame = texture(sTD2DInputs[0], uv);
    vec4 history = texture(sTD2DInputs[1], uv);
    vec4 effected = mix(currentFrame, history, 0.75);
    fragColor = TDOutputSwizzle(mix(currentFrame, effected, clamp(uMix, 0.0, 1.0)));
}
"""


TEMPORAL_RENDER_TEMPLATE = """// Render pass. Input 0 is current state; input 1 is the source image.
uniform float uMix;

layout(location = 0) out vec4 fragColor;

void main()
{
    vec2 uv = vUV.st;
    vec4 state = texture(sTD2DInputs[0], uv);
    vec4 source = texture(sTD2DInputs[1], uv);
    fragColor = TDOutputSwizzle(mix(source, state, clamp(uMix, 0.0, 1.0)));
}
"""


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("slug", help="Effect id suffix, for example chromatic-smear")
    parser.add_argument("name", help="Human-readable effect name")
    parser.add_argument("category", help="Package category and id namespace")
    parser.add_argument("--version", default="1.0.0")
    parser.add_argument("--model", choices=PROCESSING_MODELS, default="single_pass")
    parser.add_argument("--gpu-cost", choices=GPU_COSTS, default="low")
    parser.add_argument("--capability", action="append", choices=CAPABILITIES, default=[])
    parser.add_argument("--history-frames", type=int, default=0)
    parser.add_argument("--inputs", type=int, choices=range(1, 9), default=1, metavar="1-8")
    parser.add_argument("--description", default=None)
    return parser


def _validate_slug(value: str, label: str) -> str:
    if SLUG_RE.fullmatch(value) is None:
        raise SystemExit(f"{label} must contain lowercase letters, numbers, and single hyphens")
    return value


def _validate_version(value: str) -> str:
    try:
        parsed = Version.parse(value)
    except ValidationError as exc:
        raise SystemExit("--version must be valid SemVer 2.0.0") from exc
    normalized = str(parsed)
    if normalized != value or Path(value).name != value or value in {".", ".."}:
        raise SystemExit("--version must be a single canonical SemVer 2.0.0 path segment")
    return value


def _write_text(path: Path, value: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(value, encoding="utf-8", newline="\n")


def scaffold(args: argparse.Namespace) -> Path:
    slug = _validate_slug(args.slug, "slug")
    category = _validate_slug(args.category, "category")
    version = _validate_version(args.version)
    if args.history_frames < 0 or args.history_frames > 64:
        raise SystemExit("--history-frames must be between 0 and 64")
    if args.model in {"temporal", "simulation"} and args.history_frames < 1:
        raise SystemExit("temporal and simulation effects require --history-frames 1 or greater")

    package_id = f"tdimagefx.{category}.{slug}"
    packages_root = PACKAGES.resolve()
    package_root = (PACKAGES / package_id / version).resolve()
    try:
        package_root.relative_to(packages_root)
    except ValueError as exc:
        raise SystemExit("package destination must stay inside the packages folder") from exc
    if package_root.exists():
        raise SystemExit(f"refusing to overwrite existing package: {package_root}")

    safe_name = package_id.replace(".", "_").replace("-", "_")
    shader_name = slug.replace("-", "_") + ".frag"
    shader_path = f"shaders/{shader_name}"
    capabilities = list(dict.fromkeys(args.capability))
    if "history" in capabilities and args.history_frames < 1:
        raise SystemExit("the history capability requires --history-frames 1 or greater")
    input_count = args.inputs
    if args.model in {"temporal", "simulation"}:
        capabilities = list(dict.fromkeys([*capabilities, "history"] if args.model == "temporal" else [*capabilities, "history", "simulation"]))
        input_count = max(input_count, 1)
    if input_count > 1:
        capabilities = list(dict.fromkeys([*capabilities, "second_input"]))

    inputs = [
        {
            "id": "image",
            "family": "TOP",
            "required": True,
            "semantic": "source",
            "role": "source_image",
        }
    ]
    for index in range(1, input_count):
        inputs.append({
            "id": f"input_{index + 1}",
            "family": "TOP",
            "required": True,
            "semantic": "auxiliary",
            "role": "auxiliary_image",
        })

    passes = [shader_path]
    if args.model == "multi_pass":
        capabilities = list(dict.fromkeys([*capabilities, "multi_pass"]))
        passes.append("shaders/pass2.frag")
    elif args.model in {"temporal", "simulation"}:
        passes.append("shaders/render.frag")

    parameters = [
        {"id": "enable", "name": "Enable", "type": "toggle", "default": True},
        {"id": "mix", "name": "Mix", "type": "float", "default": 1.0, "min": 0.0, "max": 1.0, "uniform": "uMix"},
    ]
    if args.model in {"temporal", "simulation"}:
        parameters.append({"id": "reset", "name": "Reset", "type": "pulse", "default": False})

    processing = {
        "model": args.model,
        "gpu_cost": args.gpu_cost,
        "capabilities": capabilities,
        "passes": passes,
        "history_frames": args.history_frames,
        "pass_scale": 1.0,
        "iterations": 1,
    }
    if args.model in {"temporal", "simulation"}:
        processing["state_pass"] = shader_path
        processing["render_pass"] = "shaders/render.frag"

    manifest = {
        "schema_version": 1,
        "id": package_id,
        "name": args.name,
        "version": version,
        "fx_api": "1.0",
        "kind": "effect",
        "category": category,
        "channel": "experimental",
        "description": args.description or f"Scaffold for the {args.name} image effect.",
        "publisher": "TD ImageFX Library",
        "license": "MIT",
        "entrypoints": {
            "shader": shader_path,
            "touchdesigner_component": f"tox/{safe_name}.tox",
        },
        "inputs": inputs,
        "outputs": [{"id": "image", "family": "TOP", "role": "image"}],
        "parameters": parameters,
        "compatibility": {
            "touchdesigner_min_build": 2022.2,
            "touchdesigner_max_build": None,
            "os": ["windows", "macos"],
            "architectures": ["x86_64", "arm64"],
        },
        "permissions": {"python": False, "filesystem": False, "network": False, "subprocess": False},
        "dependencies": [],
        "alpha_policy": "preserve",
        "resolution_policy": "input",
        "stateful": args.model in {"temporal", "simulation"},
        "tags": [category, "scaffold"],
        "processing": processing,
        "image_contract": {
            "color": {
                "input_space": "source",
                "working_space": "project",
                "output_space": "source",
                "reference": "display_referred",
            },
            "alpha": {"input": "any", "working": "any", "output": "any"},
            "pixel_format": {"policy": "inherit"},
            "sampling": {"filter": "linear", "edge": "clamp", "mipmaps": False},
        },
        "determinism": {"mode": "deterministic"},
        "provenance": {
            "origin": "original",
            "source": {"type": "original"},
            "examples": [],
            "presets": [],
            "known_limitations": [
                "Generated scaffold; replace the sample shader and validate the effect before release."
            ],
        },
    }
    if args.model in {"temporal", "simulation"}:
        manifest["temporal"] = {
            "reset": {
                "strategy": "pulse_parameter",
                "parameter": "reset",
                "clears": "simulation_state" if args.model == "simulation" else "history",
                "on_resolution_change": True,
                "on_input_change": False,
            },
            "warmup_frames": 0,
        }

    try:
        PackageManifest.from_data(manifest)
    except ValidationError as exc:
        raise SystemExit(f"generated manifest is invalid: {exc}") from exc

    _write_text(package_root / "package.json", json.dumps(manifest, indent=2, ensure_ascii=False) + "\n")
    template = TEMPORAL_TEMPLATE if args.model in {"temporal", "simulation"} else SHADER_TEMPLATE
    _write_text(package_root / shader_path, template)
    if args.model == "multi_pass":
        _write_text(package_root / "shaders" / "pass2.frag", SECOND_PASS_TEMPLATE)
    elif args.model in {"temporal", "simulation"}:
        _write_text(package_root / "shaders" / "render.frag", TEMPORAL_RENDER_TEMPLATE)
    return package_root


def main() -> int:
    package_root = scaffold(_parser().parse_args())
    print(package_root.relative_to(ROOT).as_posix())
    print("Next: edit the shader/manifest, then run TouchDesigner build_project.py to generate the .tox component.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
